trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  # 1) Instala JDK 21 já disponível no cache do agente
  - task: JavaToolInstaller@0
    displayName: 'Instalar JDK 21 (PreInstalled)'
    inputs:
      versionSpec: '21'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'   # não requer jdkFile

  # 2) Verifica a versão para confirmar
  - script: |
      echo "--- java -version ---"
      java -version
      echo "--- javac -version ---"
      javac -version
    displayName: 'Verificar versão do Java'

  # 3) Compilar com Maven usando JDK 21
  - task: Maven@4
    displayName: 'Maven Package com JDK 21'
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '21'
      jdkArchitectureOption: 'x64'
      goals: 'clean package'
