trigger:
- main

variables:
  azureSubscription: '98571f40-f262-45cc-b840-1fb739397b7a'
  webAppName: 'breez'
  environmentName: 'breez'
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: MavenPackageAndPublishArtifacts
    displayName: Maven Package and Publish Artifacts
    pool:
      vmImage: $(vmImageName)

    steps:
    # 1) Instala o JDK 21 do cache do agente
    - task: JavaToolInstaller@0
      displayName: 'Install JDK 21'
      inputs:
        jdkSourceOption: 'AzurePipelines'
        versionSpec: '21'
        jdkArchitectureOption: 'x64'

    # (Opcional) Verifica a versão do Java previamente instalada
    - script: |
        echo '--- java -version ---'
        java -version
        echo '--- javac -version ---'
        javac -version
      displayName: 'Verificar versão Java instalada'

    # 2) Build Maven usando o JDK 21 instalado acima
    - task: Maven@4
      displayName: 'Maven Package'
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '21'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'clean package'

    # 3) Copia o jar/war gerado para o staging
    - task: CopyFiles@2
      displayName: 'Copy Files to artifact staging directory'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/target/*.?(jar|war)'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    # 4) Publica o artifact
    - upload: '$(Build.ArtifactStagingDirectory)'
      artifact: drop

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeployLinuxWebApp
    displayName: Deploy Linux Web App
    environment: $(environmentName)
    pool:
      vmImage: $(vmImageName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Azure Web App Deploy: breez'
            inputs:
              azureSubscription: $(azureSubscription)
              appType: webAppLinux
              appName: $(webAppName)
              package: '$(Pipeline.Workspace)/drop/**/*.jar'
